apiVersion: v1
kind: Secret
metadata:
    name: dummy-secret
    namespace: default
type: Opaque
stringData:
    hello: ENC[AES256_GCM,data:lmh1MFE=,iv:5aeNc4gdlidc7DwFAdMLFrAgLX8yZw8TUJqH9bNEzOk=,tag:ysIIRQmTlY3m+JCn8FXHpw==,type:str]
sops:
    age:
        - recipient: age18zt3nnfmvqptym5k79vknf9mxzkwwfzcpgct2wkfma02mjpxwpmszrf8q9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUjlxOXpXZjRpTGZwK1JX
            MFBDbUw4dmUwTVVJdDR4bVBYU2UwRXA5Qmx3CjlBNUVkbEVPdmJ6WllHWElpSGZO
            bWdjejhNSmp0OEhMN09WdHBvT2xDWjAKLS0tIFBDVG1kUjNIeE0xbE5TcVg4a0Ja
            TlBDekdjblkyZEVMWkdhY0VmVlY5Q1UKq2gVFDh7lxScXj946GhfDO+OzOG03r2U
            7xbNw3FkDwQKCezDqIUP1G+eQ0UOHRIUgKqrTgaLvUd5/FwuVVCCPg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16s38lv6dgcu2apqaft92g5usxqg4fhrwfz7qqusfwn6tkjj3ddeqfmhua7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpbHQyMWoyTys2ZnptU1dt
            a2Joak42ZklIQlNjdE9TYkZmNGVyajFUMkFrCjNDcHZKbXVteEJPOFN3a3RJaGdO
            bkRXSHlwZWJHaTVsN1gxYkR2QTRiZU0KLS0tIDlyM3hnVzA3UzVGS0QyYkdNZXAv
            dzhSQWpjdWRwaFo5QzgxemZCUW9yaXcKkKVXDin3Us6jD2k2WpHuD/IQv4XA1d0S
            TJ7F6p6zPduaR75B+IKuerRFBMfls2cBhsf/QDREoJwWnb7OSlNKSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-27T16:33:25Z"
    mac: ENC[AES256_GCM,data:yIQU1TD4kao6MrQ+ZPCDwp4z5ubdT4fqDuy7KrRxShrNRjQOXOju+HIpj//vLat4glbpTPAYIPGDZGO3ACQ85aaAj6waDToFPYU7e4HNnqxFcINRoVCuvcdAW8BOiL5St2SazaKuOhhxuPYTc1BXzXEbkwGk5DmiTWVFS7p/Z6k=,iv:ftzMYkiyTCgI6ET1jk4c2ngMCPQSbHhIu+VcZ3DVqaw=,tag:LafhvrtXXmB4r2jeNfAFJQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
