apiVersion: v1
kind: Secret
metadata:
    name: dummy-secret
    namespace: default
type: Opaque
stringData:
    hello: ENC[AES256_GCM,data:lmh1MFE=,iv:5aeNc4gdlidc7DwFAdMLFrAgLX8yZw8TUJqH9bNEzOk=,tag:ysIIRQmTlY3m+JCn8FXHpw==,type:str]
sops:
    age:
        - recipient: age18zt3nnfmvqptym5k79vknf9mxzkwwfzcpgct2wkfma02mjpxwpmszrf8q9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQnQvc2xZcnlpbnIxZ3Ju
            NG1JSDNXVzlvd2lwQnlxejlHcVVXK2xGWUFNCk9kRTBZWVI0MUtzUGN6NU5nUnJW
            YlZQRXZPS3Z4T29hWHdoQXRpSmZkek0KLS0tIGxYMGltS24xdkdDOEM5V2ZaU29U
            WEFmcHRtZXpJcEFHSFlhWm5Ld2IxMnMKmreDfiH8HgOfKTQ5CiISawMZIKC3rSqX
            u/mQsfpH8GXK7qGK8o5W1Yd2BZt6zjXR6K+Y+HtyTYhMA6PB4Enrrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-27T16:33:25Z"
    mac: ENC[AES256_GCM,data:yIQU1TD4kao6MrQ+ZPCDwp4z5ubdT4fqDuy7KrRxShrNRjQOXOju+HIpj//vLat4glbpTPAYIPGDZGO3ACQ85aaAj6waDToFPYU7e4HNnqxFcINRoVCuvcdAW8BOiL5St2SazaKuOhhxuPYTc1BXzXEbkwGk5DmiTWVFS7p/Z6k=,iv:ftzMYkiyTCgI6ET1jk4c2ngMCPQSbHhIu+VcZ3DVqaw=,tag:LafhvrtXXmB4r2jeNfAFJQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
