apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:6/9viOiAmTYyQDS4R9v2PvatnxzrWK9BCg2XrkqEiFn2BChD8ortjw==,iv:y9+1EnHF4Y8h6mougxJ5BrQB2acXGbOHjW6D9dE4vWc=,tag:ofFRGCHZn6TbqkZ7HECjKA==,type:str]
sops:
    age:
        - recipient: age18zt3nnfmvqptym5k79vknf9mxzkwwfzcpgct2wkfma02mjpxwpmszrf8q9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHMTV1TnlUWUkvWnI1bDNk
            OTZCcUNXeVB5ZEZRbDJkZjEyb2V2U2JWQWlNCmo1QTdxdXVhSVhrSnJockthTWJy
            V01vZ1MxQ2U5ODViVUVqOEU2Z2dmNDgKLS0tIHRQZzk2RzBmSS9OVU1EVWNFWEdp
            Y05XaDdzNHh5d2xxNmtKMnlTd20zTkUKLeop2I2jBD+kczNaMk774+HF7w5vNp0Z
            cwVRf6dAe8p/BcoiNCeZw3ODxjcP54x4CQRHqM18/Y18wX4F20SUiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-27T20:58:52Z"
    mac: ENC[AES256_GCM,data:c5baA0rY9XdjH5HGL9h5obeOjx/TCypiSrBWUkrvckzy8Ht1zwa+X9HoerxZUH4UpKfUqxZ44S2sSOEYtAU/IzMTGYO7CavPad8yGFzXTinvmSwFCCcIjplEEIc33Ab82v1ZKwFGMSZue6ilDLFCsUnEgaQGtfsGsm/oH5FODaU=,iv:nFTYY34lzonFIDV9zCakPu4uyZJ6hxC22Dx9CKGv2Ak=,tag:JzgYD9/TceXNuaHN78jRcg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
