apiVersion: v1
kind: Secret
metadata:
    name: ghcr-cred
    namespace: svc-kochen
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:mRV9JELgHPSPEsP8uQ5/FIGnG8wiKpQ7ILPt3XtBXl0IGU8uPeS5dMq/tVQbjHgJdIbMH14ZNi04pGN8jxxXIHcXAmXh08Q7U9SrcWEd2eiQBTTkH5E8YAtJXU0oRoHud6Bb9yqnCWNI9wIlTWF39Zr1yObU9BMHT1dflpdu8tnCBkTdt2BWOFNbo5WNu8du8V0HRntzeI6+dVHi6s3PJ73nr1nKVUDBE+Bj9jMFFgN3qB4IpQLWHXnxcDvTANGexpj4PXDvAF8HdEssg6sCxnKLqsIjd97+eeEUPTDkQlJRzU/KzechY0qLqI48PvgV59m+oWbgkf85GagVe61aztdKpJp1OZtCkrUVMHI=,iv:JwJ2ZE0vV0wgYSfMepGvLg7NRwnZf32jcLSRx4t5aPE=,tag:6hDohdT2LDYJr8yW3T/IXg==,type:str]
sops:
    age:
        - recipient: age18zt3nnfmvqptym5k79vknf9mxzkwwfzcpgct2wkfma02mjpxwpmszrf8q9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dms1R2F4YUZ0OE5SY2Jo
            THJaOTloOTA3NHBMRGFVYVpHNnFDVTBGbEN3CkQvOVdRWGt0WTZzQ21ZR1U2QTJv
            NS9mcXBJM2k0RTllakUyL2ZqWmFQMmsKLS0tIHJhb2UxUGVSSjI5VXZlVXkxZmZ4
            dHM4djhISFNVM3BDY1pndm9PS0I4VGsKn+mYX0PiJczBy8EWabU4wuc/lPQbKnBg
            PIXsMsOGuvjJ/f3VnQ/xH6bkHxNsJfoqbj3fqikgbDQ2soA6t8a5hA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-27T19:53:53Z"
    mac: ENC[AES256_GCM,data:pqv4fwY4PknECBwJSX0+92baF3hPuGHwHpGj9e6fxd0A4v6CX1OU46h/XLRjKUAO2FfEEUgqLCEtgJdMCvJzAcEszE0Zj9DqbBUv69cKx/irwmKlaPPEDLDkjfEtm4aSLHL2sQYfXmhbxazPqDhuMlRdbs3nAJ2S1NJzobK6xO0=,iv:/tYPEjZrGvwtmtPp8k3NZc+IhaTD5Qi3O1cmyYFioU4=,tag:vym9m1dSNcMlxYIMwkBgEA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
