apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./infra/cert-manager
  - ./infra/metallb
  - ./infra/metallb/metallb-helm.kustomization.yaml
  - ./infra/metallb/metallb-config.kustomization.yaml
  - ./svc-stirling
  - ./svc-trilium
  - ./svc-kochen
  - ./svc-ddns
