apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-helm
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/infra/longhorn
  prune: true
  wait: true
  targetNamespace: longhorn-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  commonMetadata:
    labels: { app: longhorn }
  dependsOn: []
  patches:
    - target:
        kind: HelmRelease
        name: longhorn
      patch: |-
        - op: add
          path: /spec/install/disableWait
          value: false
  healthChecks:
    - apiVersion: apps/v1
      kind: DaemonSet
      name: longhorn-manager
      namespace: longhorn-system
    - apiVersion: apps/v1
      kind: Deployment
      name: longhorn-admission-webhook
      namespace: longhorn-system
    - apiVersion: v1
      kind: Service
      name: longhorn-admission-webhook
      namespace: longhorn-system

