apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secrets
    namespace: svc-ddns
type: Opaque
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:MEVRgJrq/WDdUsMhhTV50Gl3C0KGcTIPQ8zEXtEeNcGYe9+pHAUDqg==,iv:M0u6HSrZOyRtH+SDLE4hz80TPaql2Ds9FPaVg8j3SHg=,tag:klTrAz8cS7g01631sntI5Q==,type:str]
sops:
    age:
        - recipient: age18zt3nnfmvqptym5k79vknf9mxzkwwfzcpgct2wkfma02mjpxwpmszrf8q9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTHg4SUtwaDRzUGlwZGd5
            UnRKTDA0TE9qTFEyWDltSlkxOGdxZ3hCUHhRCk43cHNTS3kyLytodkZ3aE1WcnNw
            eWJiWGhMMHIxRStiWW1HRUE4YnBORmsKLS0tIE5OenJ3dktvZzNmRytxRW9xRzZw
            TlhmbFZESHpqbVdWdmg4MzZRUWVHK2sK5pKI11JZOBe+8MLFcpEx7CfiKKzAkye2
            xgXemNvySgjKyfU3RN6pH3ntgB0FEXylnsMtWa6gHHxJSuBRoEPEmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-27T20:22:12Z"
    mac: ENC[AES256_GCM,data:AGtlX8I7+/dp5buIuoHtoEPWaNKlsqL34WwJ1UK0hk134oC8G2utmH5JaU+D7YGAgMGFOm4bZQFLqyyYhPO9icVO/oOfb6Oj4OZ1BiJfCyGwrbfy6D9c2eodle1Va+1FPGdOAzSFK7r/f9PCmLIrmEoLOJ9IJQrjOsqi2Nt8cb0=,iv:++ZhRo35kJQjWjVrP/KonLUl5faJX7o3adKV8AOGKzA=,tag:bj3UGUFnfxQ4DAPlhpedhQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
