apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secrets
    namespace: svc-ddns
type: Opaque
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:MEVRgJrq/WDdUsMhhTV50Gl3C0KGcTIPQ8zEXtEeNcGYe9+pHAUDqg==,iv:M0u6HSrZOyRtH+SDLE4hz80TPaql2Ds9FPaVg8j3SHg=,tag:klTrAz8cS7g01631sntI5Q==,type:str]
sops:
    age:
        - recipient: age18zt3nnfmvqptym5k79vknf9mxzkwwfzcpgct2wkfma02mjpxwpmszrf8q9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SW95MlJxelVMVmZUa3d2
            MHN2T29SQnFRRXhVZ1QzeU9CdlZLQ0hvWTFFCmhZb2daTE1rOWl1K3VJeU9CaFRU
            UndhNkluNnlTa3RUdDhud0FLK1NwZmcKLS0tIFFLeEtTN2pHQXZGc2J0eHZUeG5k
            U0NrQlVsZm1JQm9Fb3FhaHN1UG9FT2sKV6yVvim2UgtP1oOuVQEjrgy7XZLi2Pn6
            HAODcTcDCBX9QCweHn83pnj9nt27MVtZl4ZdjiwbYERAIE1m2EhPNg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16s38lv6dgcu2apqaft92g5usxqg4fhrwfz7qqusfwn6tkjj3ddeqfmhua7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZ25MWk9ZVVJJdjFYUFU1
            SlA3S1NrYldFeGNSZXZQcmFmTWdLSTJVZERZCmVmQXVQRkR0ZTVBbk9NVFN6bzE4
            amNBV21qcWhtbVdYZTlOTjBMamtlblUKLS0tIE5KMkptdE9aaURrQ1gxeEcvaldi
            UDZoaWJIckJlbTdwZDErUUJTWGN2cXcKncrUN8bCDzZquphz9XMSE8SI31fl64FR
            xYSqHPeEpNO3GJq5aU1XmsrhG+zeKlYxRflJ65myxrRNuO1nkytp1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-27T20:22:12Z"
    mac: ENC[AES256_GCM,data:AGtlX8I7+/dp5buIuoHtoEPWaNKlsqL34WwJ1UK0hk134oC8G2utmH5JaU+D7YGAgMGFOm4bZQFLqyyYhPO9icVO/oOfb6Oj4OZ1BiJfCyGwrbfy6D9c2eodle1Va+1FPGdOAzSFK7r/f9PCmLIrmEoLOJ9IJQrjOsqi2Nt8cb0=,iv:++ZhRo35kJQjWjVrP/KonLUl5faJX7o3adKV8AOGKzA=,tag:bj3UGUFnfxQ4DAPlhpedhQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
